"""Rebuild fonts/tw-kai/ from the official TW-Kai font.

TW-Kai (全字庫正楷體) is Taiwan's Ministry of Education standard Kai font, published by
the Ministry of Digital Affairs. It is too big to ship whole, so this splits it into
~100 small WOFF files using the same character groups Google Fonts uses for Noto Serif TC
(grouped by how common each character is). Browsers then download only the pieces a page
needs, via unicode-range in fonts/tw-kai.css.

Usage (needs Python with fonttools: pip install fonttools):
  1. Download https://www.cns11643.gov.tw/opendata/Fonts_Kai.zip and extract TW-Kai-98_1.ttf
  2. python scripts/build_tw_kai.py path/to/TW-Kai-98_1.ttf
"""
import os, re, sys, urllib.request
from multiprocessing import Pool
from fontTools import subset
from fontTools.ttLib import TTFont

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(ROOT, 'fonts', 'tw-kai')
NOTO_CSS = 'https://fonts.googleapis.com/css2?family=Noto+Serif+TC:wght@400&display=swap'
UA = 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0 Safari/537.36'

def parse_range(r):
    cps = set()
    for part in r.split(','):
        part = part.strip()[2:]
        if '-' in part:
            a, b = part.split('-'); cps |= set(range(int(a, 16), int(b, 16) + 1))
        else:
            cps.add(int(part, 16))
    return cps

def format_range(cps):
    cps = sorted(cps); out = []; i = 0
    while i < len(cps):
        j = i
        while j + 1 < len(cps) and cps[j + 1] == cps[j] + 1: j += 1
        out.append('U+%x' % cps[i] if i == j else 'U+%x-%x' % (cps[i], cps[j])); i = j + 1
    return ','.join(out)

def build(args):
    src, i, cps = args
    opts = subset.Options(); opts.flavor = 'woff'; opts.hinting = False
    opts.name_IDs = [0, 1, 2, 3, 4, 5, 6, 13, 14]; opts.notdef_outline = True
    font = subset.load_font(src, opts)
    s = subset.Subsetter(opts); s.populate(unicodes=cps); s.subset(font)
    subset.save_font(font, os.path.join(OUT, 'tw-kai-%d.woff' % i), opts)

if __name__ == '__main__':
    src = sys.argv[1]
    css = urllib.request.urlopen(urllib.request.Request(NOTO_CSS, headers={'User-Agent': UA})).read().decode()
    have = set(TTFont(src, lazy=True).getBestCmap())
    groups = [sorted(parse_range(r) & have) for r in re.findall(r'unicode-range:\s*([^;]+);', css)]
    groups = [g for g in groups if g]
    for f in os.listdir(OUT):
        if f.endswith('.woff'): os.remove(os.path.join(OUT, f))
    with Pool() as pool: pool.map(build, [(src, i, g) for i, g in enumerate(groups)])
    with open(os.path.join(ROOT, 'fonts', 'tw-kai.css'), 'w', encoding='utf-8', newline='\n') as f:
        f.write('/* Generated by scripts/build_tw_kai.py. TW-Kai (全字庫正楷體), see fonts/tw-kai/LICENSE.txt */\n')
        for i, g in enumerate(groups):
            f.write("@font-face{font-family:'TW-Kai';font-weight:400;font-display:swap;"
                    "src:url(/fonts/tw-kai/tw-kai-%d.woff) format('woff');unicode-range:%s}\n" % (i, format_range(g)))
    print('wrote', len(groups), 'slices covering', sum(map(len, groups)), 'characters')
